package com.skaly.fashion_backend.ai.domain;

import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class ChatMessageModelTest {

    @Test
    void builder_shouldSetDefaultValues() {
        ChatMessageModel message = ChatMessageModel.builder()
                .role("user")
                .content("Hello, how can I help you?")
                .build();

        // ID should be generated by builder
        assertNotNull(message.getId());
        assertEquals("user", message.getRole());
        assertEquals("Hello, how can I help you?", message.getContent());
        // createdAt should be set by builder
        assertNotNull(message.getCreatedAt());
    }

    @Test
    void builder_shouldSetRoleToUser() {
        ChatMessageModel message = ChatMessageModel.builder()
                .role("user")
                .content("Test message")
                .build();

        assertEquals("user", message.getRole());
    }

    @Test
    void builder_shouldSetRoleToAssistant() {
        ChatMessageModel message = ChatMessageModel.builder()
                .role("assistant")
                .content("I can help you find products")
                .build();

        assertEquals("assistant", message.getRole());
    }

    @Test
    void updateContent_shouldUpdateMessage() {
        ChatMessageModel message = ChatMessageModel.builder()
                .role("user")
                .content("Original content")
                .build();

        message.setContent("Updated content");
        assertEquals("Updated content", message.getContent());
    }

    @Test
    void builder_shouldGenerateDifferentUUIDs() {
        ChatMessageModel message1 = ChatMessageModel.builder()
                .role("user")
                .content("Message 1")
                .build();

        ChatMessageModel message2 = ChatMessageModel.builder()
                .role("user")
                .content("Message 2")
                .build();

        assertNotNull(message1.getId());
        assertNotNull(message2.getId());
        assertNotEquals(message1.getId(), message2.getId());
    }

    @Test
    void createdAt_shouldBeSetAutomatically() {
        LocalDateTime before = LocalDateTime.now().minusSeconds(1);
        
        ChatMessageModel message = ChatMessageModel.builder()
                .role("user")
                .content("Test")
                .build();

        LocalDateTime after = LocalDateTime.now().plusSeconds(1);
        
        assertNotNull(message.getCreatedAt());
        assertTrue(message.getCreatedAt().isAfter(before) || message.getCreatedAt().isEqual(before));
        assertTrue(message.getCreatedAt().isBefore(after) || message.getCreatedAt().isEqual(after));
    }
}